// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJIA_GSqrMcwkShz7GhD2VMpdepP6bOcA',
    appId: '1:150384321181:web:2d1a27cdec83e73af2ea74',
    messagingSenderId: '150384321181',
    projectId: 'mycpstats',
    authDomain: 'mycpstats.firebaseapp.com',
    storageBucket: 'mycpstats.appspot.com',
    measurementId: 'G-5CTK7R02QR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnSJO5-jKptbbEZ2lsv3zQAoqiuLTTSRM',
    appId: '1:150384321181:android:96181e7d04345e81f2ea74',
    messagingSenderId: '150384321181',
    projectId: 'mycpstats',
    storageBucket: 'mycpstats.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDdeqLAPMMbo7Jf39N6iqmpVAhDGPApAY',
    appId: '1:150384321181:ios:36fa1da3fab1ebd3f2ea74',
    messagingSenderId: '150384321181',
    projectId: 'mycpstats',
    storageBucket: 'mycpstats.appspot.com',
    iosBundleId: 'com.example.myCpStats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDdeqLAPMMbo7Jf39N6iqmpVAhDGPApAY',
    appId: '1:150384321181:ios:7e7e0da88fabe585f2ea74',
    messagingSenderId: '150384321181',
    projectId: 'mycpstats',
    storageBucket: 'mycpstats.appspot.com',
    iosBundleId: 'com.example.myCpStats.RunnerTests',
  );
}
